# Config version
version: 0.3.2

# HTML Head settings
html:
  title: Links | Mi Nombre

# Main container settings
main:
  title: Mi Nombre

# Blocks list
blocks:
  - title: Instagram
    icon: instagram
    url: https://www.instagram.com/lacryptaok/

  - title: Twitter
    icon: twitter
    url: https://twitter.lacrypta.com.ar

  - title: Github
    icon: github
    url: https://github.com/lacrypta
