# Config version
version: 0.3.0

# HTML Head settings
html:
  title: La Crypta | Custodial # Este es el nombre que aparece en la pestaña de navedagor

# Main container settings
main:
  title: LA CRYPTA Custodial # Aca podes poner tu nombre o el de tu producto

# Blocks list
blocks:

# Estos bloques los podes editar cambiando SOLO el texto que está en blanco
# Si querés eliminar una red social es tan facil como borrar los 3 campos correspondientes (ttile, icon, url)

  - title: LinkedIn # Este es el nombre del botón 
    icon: linkedin # Este es el nombre del icono (si queres añadir una red social nueva, prestá atencion que es todo con minuscula)
    url: https://linkedin.com/in/TU-USUARIO # Link a donde redireccionará al hacer click

  - title: Github
    icon: github
    url: https://github.com/TU-USUARIO
  
  - title: Twitter
    icon: twitter
    url: https://twitter.com/TU-USUARIO

  - title: Sitio Web
    icon: url
    url: https://www.TU-WEB.com

  - title: Telegram
    icon: telegram
    url: https://t.me/TU-USUARIO
