# Config version
version = "0.3.0"

# HTML Configuration
[head]
title = "La Crypta | Links"

# Main Configuration
[main]
title = "LA CRYPTA"

######### Blocks START HERE #########

[[blocks]]
icon = "instagram"
title = "Instagram"
url = "https://instagram.lacrypta.com.ar"

[[blocks]]
icon = "discord"
title = "Discord"
url = "https://discord.lacrypta.com.ar"

[[blocks]]
icon = "voluntary"
title = "Quiero participar!"
url = "https://docs.google.com/forms/d/e/1FAIpQLSfMM_fDXrBVlxujPy4yhYRuhHWrtPSvoD8QRCKuHzZXgsFFzg/viewform"

[[blocks]]
icon = "github"
title = "Github"
url = "https://github.lacrypta.com.ar"

[[blocks]]
icon = "twitter"
title = "Twitter"
url = "https://twitter.lacrypta.com.ar"

[[blocks]]
icon = "url"
title = "Sitio Web"
url = "https://www.lacrypta.com.ar/"

[[blocks]]
icon = "whatsapp"
title = "WhatsApp"
url = "https://api.whatsapp.com/send/?phone=%2B541131080456&text=Hola+como+estan&type=phone_number&app_absent=0"